name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Запуск тестів
        run: make test

      - name: Збірка проєкту
        run: make
